### ISSUE TITLE
work well ,but should update docs

### ISSUE THREAD

**Issue by aizigao** [psychoo118/react-native-web-image-loader#3]
```js
 {
      test: /\.(gif|jpe?g|png|svg)$/,
      loader: 'react-native-web-image-loader?name=[name].[ext]&scalings[@2x]=2&scalings[-3x]=3'
  },
```

I was confused about much time ,should update https://www.npmjs.com/package/react-native-web-image-loader
👍

**Comment by aizigao** [comment]
en... I use above code, has some problem now，it seem just works once.
![image](https://user-images.githubusercontent.com/14126445/28675461-87ea2cc2-731a-11e7-91dc-5ccf225dec1f.png)
* this is my folder 
![image](https://user-images.githubusercontent.com/14126445/28675515-ad839144-731a-11e7-9b81-8baec4f743cb.png)

**Comment by psychoo118** [comment]
thanks for letting me know about that! I fixed it earlier today.
